[theme]
primaryColor = "#465FFF"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#101828"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
