[theme]
primaryColor = "#2D6A4F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#D8F3DC"
textColor = "#0B1D14"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
